### PR TITLE
Add Policy based content providing talk

### PR DESCRIPTION
**Pull request by thibmeu**
within IPFS as Infra track

@mikeal I'm not sure how slot would look like. I stick to the default 45 to make refactoring easier.
~20min+5/10min question should suffice.

### CODE REVIEW

**Comment by b5** [comment]
👋 @thibmeu, thanks so much for filing! we made a few changes to the "IPFS as Infra" track, including a rename to "Connecting IPFS". I believe your talk is still very much a great candidate for this track. With regard to timing, I believe @mikeal was thinking along similar lines for talk length, targeting 30 minutes total.

Would you mind updating your PR against these latest changes? Thanks!

**Comment by thibmeu** [comment]
@b5 I have updated the commit. I pushed the Unconf to 14:30, to keep 1h for the writable gateway discussion.

**Comment by mikeal** [comment]
We want to keep all the formal talks in the timeslots before Lunch. I may chop all the talk times down to 20 minutes if we run out of room, but there’s still open room for a 30m slot before lunch you should move this into. I don’t want to take 30m out of the Unconf time.

**Comment by mikeal** [comment]
Actually, plan on 20m, I’m going to cut all the talks down to 20m.

**Comment by mikeal** [comment]
In order to avoid merge conflicts I included this talk in https://github.com/ipfs-shipyard/ipfs-thing-2022/pull/84

**Pull request closed without merging**
