### PR TITLE
Merge Data Agony and Data Transfer Tracks Together

### PR DESCRIPTION
**Pull request by hannahhoward**
Per discussion with @b5 this PR takes the latest workshop list from @aschmahmann on the Data Agony track and the current data transfer track to create a single, one and one half day long 3 part "Data and IPFS" track.

Part 1 is the structured content from Data Agony and now takes place on Wednesday, 7-13-22 in the afternoon from 1-5pm
Part 2 is the structured content from Data Transfer and still takes place in the morning of Thursday, 7-14-22, from 9am - 12pm
Part 3 is an open unconf for topics address data models or transfer, or any other subject in this realm of issues, and is in the afternoon on Thursday, 7-14-22, from 1pm - 5pm.

I also did rename a few other tracks so that the "IPFS and Data" tracks line up on the chart in the same way the content-routing tracks do.

Note @b5 I haven't had a chance to follow up with @aschmahmann since our conversation so we should probably make sure to get his approval prior to merge.

### CODE REVIEW

**Comment by aschmahmann** [comment]
Yep, will follow up later today, reaching out to @RangerMauve also for any timing constraints.

**Comment by aschmahmann** [comment]
@hannahhoward pushed some updates. Wouldn't say they're set in stone by any means and suggestions welcome, but figure it's a pretty good description of what we've got at the moment.

I'd like to have a slot to present on the manifetch/lightning storm data transfer approach. I could probably squeeze it into the data modelling section as it relates to my proposal on block limits, but could also do it in the open slots time on Wednesday.

**Comment by aschmahmann** [comment]
Also, added a callout here for folks interested in the modelling side of things to answer a prompt on https://pl-strflt.notion.site/Your-vision-for-IPFS-and-Data-15087c9885db48df8af4f11fc62d15e1, to help us all understand where each other are coming from better and give people time to prepare for those discussions. Fill it out when you can 😄, the earlier you do the more time people can ask clarifying questions or comments for you.

**Comment by hannahhoward** [comment]
@aschmahmann there already is a section on manifests in the data transfer section. I would say if we can cover it there and if we need to dive deeper into specifically manifetch / lightning storm we can unconf it.

**Comment by hannahhoward** [comment]
@aschmahmann one problem: the notion site I imagine is not editable by anyone who is not Starfleet.

**Comment by hannahhoward** [comment]
I went ahead and turned on global editing -- security through obscurity should handle the rest for preventing people who aren't otherwise connected to IPFS thing from making changes

**Comment by aschmahmann** [comment]
Oh sorry I thought I did that, thanks 🙏

**Comment by hannahhoward** [comment]
Alright we're both mostly on board and the website is very out of date, and I'm really tired of rebasing. I'm merging!

**Pull request merged**
